### ISSUE TITLE
fails when hpkp_days is null

### ISSUE THREAD

**Issue by Jean-Daniel** [plinss/acmebot#33]
The doc says hpkp_days can be 0 or null to disable it (which should be the default as hpkp is a dead end and is going to be remove from all browsers later this year).

But when set to null, it cause the script to failed because int and None can't be compared.

```python
Traceback (most recent call last):
  File "./acmebot", line 2945, in <module>
    AcmeManager.Run()
  File "./acmebot", line 144, in Run
    manager.run()
  File "./acmebot", line 2913, in run
    self.process_certificates(self._setting('follower_mode'), self.args.private_key_names)
  File "./acmebot", line 2172, in process_certificates
    if (0 < hpkp_days) and (self._directory('hpkp')):
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

**Comment by plinss** [comment]
Fixed by 5df481c23c59ab47a54cc3c0949d822b64513ed4
